version: '3.8'

services:
  goshorty:
    image: goshorty:latest
    build: .
    container_name: goshorty
    environment:
      SHORTY_HOST: 0.0.0.0
      SHORTY_PORT: 1337
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PW: ''
    ports:
      - '1337:1337'
    depends_on:
      - redis
  redis:
    container_name: redis
    ports:
      - '1338:6379'
    image: 'redis:latest'
