version: '3.8'

services:
  goshorty:
    image: nimachi/goshorty:latest
    container_name: goshorty
    environment:
      SHORTY_HOST: 0.0.0.0
      SHORTY_PORT: 1337
      REDIS_HOST: localhost
      REDIS_PORT: 1338
      REDIS_PW: ""
    ports:
      - '1337:1337'
    depends_on:
      - redis
    networks:
      - goshorty
  redis:
    image: "redis:latest"
    ports:
      - '1338:6379'
    networks:
      - goshorty


networks:
  goshorty:
    driver: bridge
